tasks:
  - name: Backend
    init: |
      cd backend
      npm install
    command: |
      cd backend
      npm run start
  - name: Frontend
    init: |
      cd frontend
      npm install
    command: |
      cd frontend
      npm run start

ports:
  - port: 3000
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - ms-vscode.vscode-typescript-next
    - msjsdiag.vscode-react-native
